### ISSUE TITLE
Aktuelles Jahr abrufen

### ISSUE THREAD

**Issue by alexanderschapelt** [bundesAPI/feiertage-api#3]
Hi und danke für die API.

Es wäre super, wenn man auch das aktuelle Jahr abrufen könnte. 

Vielleicht mit `jahr=current` oder wenn der Parameter nicht angegeben wird.

**Comment by wirthual** [comment]
Hi,

Für neue Features müsstest du dich am besten direkt an Herr Richter von https://feiertage-api.de/ wenden. 

Je nachdem wie du den Aufruf der API machst, sollte es aber nicht allzu schwer sein das aktuelle Jahr auf Client Seite zu bestimmen :)

**Comment by alexanderschapelt** [comment]
Alles klar Mach' ich danke :).
Ja an sich wäre das kein Problem, aber ich will die Freitage in Excel einbinden und da ist das mit dynamischen abfragen so eine Sache...

**Comment by lordwebbie** [comment]
Hi! 

Ich hab es aus Zufall gerade mitgelesen. Du hast völlig recht. Habe es nun umgebaut, sodass der jahr-Parameter nur noch optional ist. Du kannst nun z.B. einfach `https://feiertage-api.de/api/` aufrufen, um die Feiertage des aktuellen Jahres zu bekommen.

LG Julian

Edit: Nicht wundern, dass die Doku noch nicht angepasst ist. Ich relaunche in den nächsten Tagen die ganze Doku-Seite, deshalb fasse ich die alte Seite jetzt nicht mehr an.

**Comment by wirthual** [comment]
Cool. Werde Mal schauen da sich das in die API description bekomme.

**Comment by wirthual** [comment]
Ich habe das required flag für das Jahr entfernt.  Sollte jetzt klappen.
