### ISSUE TITLE
Kennzeichnung von Hochfeiertagen

### ISSUE THREAD

**Issue by asieverding** [bundesAPI/feiertage-api#4]
Hallo, die API ist super und hilfreich um automatisiert Feiertage in ein digitales System zu importieren.
Wäre es möglich, für die Feiertage eine Kennzeichnung hinzuzufügen, ob es sich bei dem jeweiligen Feiertag um einen Hochfeiertag handelt oder nicht?

Liebe Grüße

**Comment by wirthual** [comment]
Hi,

evtl. Kann @lordwebbie hier helfen? :)

**Comment by lordwebbie** [comment]
Hi @asieverding!
Was genau verstehst du denn unter einem "hohen" Feiertag? Geht es dir um das Arbeitszeitgesetz?

**Comment by asieverding** [comment]
Ja genau das meine ich. Wir nutzen die API um Feiertage automatisch in unser System zu importieren. Da wir im System eine Auszahlung für Bereitschaften integriert haben brauchen wir die Info, ob es sich um einen hohen Feiertag handelt oder nicht um die Vergütung richtig auszahlen zu können. Bislang machen wir das manuell, deshalb wäre diese Erweiterung der API ein Mehrwert für uns und bestimmt auch für andere Betriebe.

**Comment by lordwebbie** [comment]
Verstanden. Können wir ggf. einbauen. Hast du eine Quelle, wo man die Definition inkl. aller gültigen "hohen" Feiertage sehen kann? Und wo man ggf. auch Änderungen daran sehen kann?

Oder anders gefragt, wenn es keine einheitliche Datenbasis gibt und man alles in mehreren Quellen nachverfolgen müsste: Würdest du dich bereit erklären, diese Daten zu monitoren, damit wir die Datenbasis regelmäßig updaten können?

**Comment by asieverding** [comment]
Ok ich habe mich nochmal schlau gemacht. Anscheinend sind die hohen Feiertage nicht gesetzlich, sondern über Manteltarifverträgen der jeweiligen Branchen geregelt. Ich dachte, dass das gesetzlich vorgegeben ist. Da das nicht der Fall ist, kann das natürlich auch nicht in die API mit aufgenommen werden, dementsprechend werden wir das weiterhin manuell pflegen.

Danke für die Rückmeldung!
