### ISSUE TITLE
Response der API

### ISSUE THREAD

**Issue by gowizzard** [bundesAPI/feiertage-api#5]
Hallo zusammen, ich habe eine kurze Frage zu der Rückgabe der API. Warum wurde das Format für die Feiertage nicht als Array gewählt? Oder gibt es einen Parameter mit dem ich die Rückgabe als Array anstoßen kann?

Vielen Dank im Voraus

**Comment by lordwebbie** [comment]
Hi, 

Arrays sind "nicht assoziativ", sprich diese haben keinen Key (zumindest nur einen numerischen Key). 
Eine Umsetzung als Objekt, in welchem die Länder (bzw. darunter die Feiertage) die Keys sind, ist deshalb hier die korrekte Datenstruktur.

Einen Parameter, um das Format zu ändern gibt es nicht. Aber es sollte in allen normal-gebräuchlichen Programmiersprachen kein Problem sein, dass du dir aus den Objekten Arrays mit beliebigem Format baust.

Darf ich fragen, welche Sprache du nutzt? Solltest du PHP nutzen: PHP unterstützt assoziative und nicht-assoziative Arrays. ein einfaches "json_encode(STRING)" gibt dir ein Objekt zurück, ein "json_encode(STRING, true)" gibt dir einen assoziativen Array zurück.

Viele Grüße!

**Comment by gowizzard** [comment]
Hallo, aktuell teste ist die neue Platform von Postman Flows und teste mich gerade so damit durch. Ich muss mal schauen, wie dort die Daten manipuliert bekommen, deshlab habe ich auch aktuell noch ein paar Einschränkungen und nicht die Freiheiten, die eine Programmiersprache mit sich bringt. 

Danke dir!
