### ISSUE TITLE
Gründonnerstag in Baden-Würtemberg wird als Feiertag ausgewiesen

### ISSUE THREAD

**Issue by chnbz** [bundesAPI/feiertage-api#6]
Hallo zusammen,

leider wird der Gründonnerstag als Feiertag ausgewiesen, obwohl das anscheinend nur für Schüler gilt. Wäre es möglich einen weiteren Parameter hinzuzufügen, damit man nur die arbeitsfreien Feiertage geliefert bekommt? Führt jedes zu Problem bei unseren Nutzern in BW. Bei dieser API wird der Gründonnerstag z.B. nicht als Feiertag ausgewiesen https://www.spiketime.de/feiertagapi/feiertage/BW/2024

**Comment by wirthual** [comment]
Hi,
@lordwebbie weiß vielleicht mehr.

**Comment by lordwebbie** [comment]
Ja, das ist ein valider Punkt @chnbz. Wie unter https://feiertage-api.de dokumentiert, habe ich die Daten von https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland übernommen. Dort ist der Gründonnerstag eben gelistet.
Allerdings sieht man in der Tabelle, dass er nur in BW und nur für Schuler gilt. Also eigentlich handelt es sich m.M.n. eher um Schulferien. Da ist die Wikipedia-Tabelle etwas komisch. Ich habe keine Ahnung, warum die Tabelle den Gründonnerstag dann überhaupt aufführt.

Diesbezüglich wäre meine Meinung eher, dass wir den Gründonnerstag einfach komplett entfernen müssten, da wir reine Schulferien ja gar nicht in der API haben (wollen).

Wie seht ihr das?

**Comment by wirthual** [comment]
Baden Württemberg macht eine Unterscheidung zwischen Gesetzlichen und Kirchlichen Feiertagen[1]

Und dann nochmal zwischen schulfreien und nicht schulfreien Kirchlichen Feiertagen? 

So wie ich das verstehe ist der Allgemeiner Buß- und Bettag auch ein kirchlicher Feiertag aber nicht schulfrei.

[1].  https://im.baden-wuerttemberg.de/de/service/feiertage

**Comment by lordwebbie** [comment]
So, ich habe den Gründonnerstag für alle Anfragen, die sich auf das Jahr 2024 und folgende beziehen, komplett aus der API genommen, da es sich um reine Schulferien handelt.
Für Anfragen auf Jahre vor 2024 gibt die API alles so aus, wie bisher, da ich nicht weiß, ob sich historisch jemand darauf verlässt. (Ich habe sehr mit mir gerungen, weil es ja eigentlich inkonsistent ist... :/ )

@wirthual Ich habe leider keine Berechtigungen zum Schließen von Issues. Kannst du das Issue schließen?

**Comment by floscher** [comment]
@lordwebbie Das selbe Problem besteht noch für den Reformationstag in BW und den Buß- und Bettag in BY. Könnten die auch noch entfernt werden?

Die sind auf der Wikipedia-Seite als „nur schulfrei“ markiert und die API hat als Hinweis einen Hinweis, dass das jeweilige Feiertagsgesetz schulfrei vorschreibt.

**Comment by invokablegmbh** [comment]
> Könnten die auch noch entfernt werden?

Zu den genannten Daten werden vom System Texthinweise in der API mitgegeben, die genau dies schreiben. Aber ich verstehe das Problem beim Auswerten. Beim Design der API hätte ich dies besser richtig auseinander genommen. Damals war ja einfach nur Maßgabe, dass die Feiertage-Tabelle von Wikipedia als API bereitgestellt wird. Aus Fehlern lernt man. Ich denke, dass es Zeit ist für eine API v2 mit besseren Infos... Für jetzt würde ich das gerne so belassen, da es garantiert Systeme gibt, die die Infos parsen. Die API wird schon lange recht rege genutzt.

Aber ja, ich werde eine V2 veröffentlichen, die besser (und englisch! ;) ) aufgebaut ist. Die v1-API wird dann noch weiter erreichbar, aber eben deprecated sein.

**Comment by floscher** [comment]
@invokablegmbh Kein Problem, ist ja kein großes Ding, die Ausnahmen rauszufiltern.

Nur ist es dann ja irgendwie inkonsistent, wenn der Gründonnerstag ab 2024 verschwindet, aber die anderen nur-schulfreien Tage drinbleiben. Dann passt es ja weder für die Nutzer, die die schulfreien Tage haben wollen, wie sie in Wikipedia stehen. Noch für die, die sie nicht haben wollen.

Eine v2 wäre da wirklich der Königsweg :rocket:

**Comment by floscher** [comment]
Übrigens: Gibt man aktuell den Parameter `nur_daten` an, wird der Gründonnerstag immernoch ausgegeben, ohne den Parameter wird er für die Jahre 2024 und höher ausgefiltert.

**Comment by lordwebbie** [comment]
@floscher Danke für den Hinweis. Habe ich auch entfernt. 
Das wird separat berechnet, weil "nur_daten" bedeutet, dass nur die Datumsangaben für diverse Feiertage berechnet werden. Ob das Datum ein Feiertag ist, muss dann pro Bundesland geprüft werden. Da Gründonnerstag aber in keinem Bundesland ein echter Feiertag ist, brauchen wir - völlig richtig - das Datum auch nicht mehr dort ausgeben.
